# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
orbs:
  docker: circleci/docker@1.7.0
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/check
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - docker/build:
          image: jasecharloote/auto-ddns 
          tag: slim 
      - docker/push:
          image: jasecharloote/auto-ddns 
          tag: slim 
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  example-workflow:
    jobs:
      - example-job
